### ISSUE TITLE
big "copy path to feed.rss"

### ISSUE THREAD

**Issue by mortendk** [mortendk/11tyhub.dev#1]
The number one thing is to get the user to copy the feed url and put i in their feed reader 

- [ ] Copy path button
- [ ] add to "feed" reader buttons ... it was hot af in 2002

**Comment by cconrad** [comment]
Hej @mortendk 

The URL in the big box does not work. It is missing the "hub" part of the domain.

![image](https://user-images.githubusercontent.com/584491/209848112-dd5f19c3-75b6-4dca-9856-4f422b6ea15f.png)
